### ISSUE TITLE
Remove react-table related CSS

### ISSUE THREAD

**Issue by MrHus** [42BV/ui#212]
The styling contains the following CSS rules for the react-table:

```scss
.form-control.is-valid,
.ReactTable .rt-thead.-filters .was-validated input:valid,
.ReactTable .rt-thead.-filters .was-validated select:valid,
.ReactTable .rt-thead.-filters input.is-valid,
.ReactTable .rt-thead.-filters select.is-valid,
.was-validated .form-control:valid,
.was-validated .ReactTable .rt-thead.-filters input:valid,
.was-validated .ReactTable .rt-thead.-filters select:valid {
  background-position: right calc(0.375em + 0.1875rem) center !important;
}
```

Since we no longer use react-table these styles can be removed. As this is a breaking change this should be done in `3.0.0`.
