### ISSUE TITLE
Allow style properties for all components

### ISSUE THREAD

**Issue by MrHus** [42BV/ui#432]
Allow style properties for all components, this way the user can style our components easier on a per case basis. This should work the same as the `className` properties which are optional on every component, and apply to the same element.

**Comment by MrHus** [comment]
I think that adding a style to each element will tempt the developer to use it too much. We already support adding a className on the container. 

The developer should create a utility CSS class and apply it, for example:

```css
.pointer-events-none {
  pointer-events: none;
}

```tsx
<Icon className="pointer-events-none"  icon="home" />
```
